task:
  freebsd_instance:
    matrix:
      image: freebsd-12-1-release-amd64
  install_script:
    - pkg install -y bash cmake fusefs-libs gettext perl5
    - ln -s /usr/local/bin/bash /bin/bash
    - ./ci/setup.sh
  script:
    - ./build.sh
  env:
    INTEGRATION: false
