task:
  name: FreeBSD
  freebsd_instance:
    image_family: freebsd-15-0-amd64-ufs
  install_script:
    - pkg install -y bash rust fusefs-libs pkgconf openssl
    - ln -s /usr/local/bin/bash /bin/bash
    - kldload fusefs || kldload fuse
  script:
    - cargo build --release
    - cargo test
    - ENCFS_LIVE_TESTS=1 cargo test --test live_mount -- --ignored --test-threads=1
  allow_failures: true

# task:
#   name: MacOS
#   macos_instance:
#     image: ghcr.io/cirruslabs/macos-runner:sonoma
#   install_script:
#     - brew tap macos-fuse-t/homebrew-cask
#     - brew install --cask fuse-t
#     - brew install pkg-config
#     - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
#   script:
#     - export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:/opt/homebrew/lib/pkgconfig:$PKG_CONFIG_PATH"
#     - mkdir -p $HOME/pkgconfig_shim
#     - if [ -e /usr/local/lib/pkgconfig/fuse-t.pc ]; then ln -s /usr/local/lib/pkgconfig/fuse-t.pc $HOME/pkgconfig_shim/fuse.pc; fi
#     - if [ -e /opt/homebrew/lib/pkgconfig/fuse-t.pc ]; then ln -s /opt/homebrew/lib/pkgconfig/fuse-t.pc $HOME/pkgconfig_shim/fuse.pc; fi
#     - export PKG_CONFIG_PATH="$HOME/pkgconfig_shim:$PKG_CONFIG_PATH"
#     - source $HOME/.cargo/env
#     - cargo build --release
#     - cargo test
#     - ENCFS_LIVE_TESTS=1 cargo test --test live_mount -- --ignored --test-threads=1
