#!/bin/sh

# This script mounts an encfs filesystem, starts a shell in the mounted
# directory, and then unmounts the filesystem when the shell exits.
# This is an equivalent of the cfssh utility for cfs.
# Contributed by David Rosenstrauch.

canonicalize() {
	cd "$1" || return
	pwd
}


case $1 in "" | -h | --help)
	echo "Usage: encfssh encrypted_directory [unencrypted-directory [-p]]"
	echo "  -p   mount the unencrypted directory as public"
	exit 1
	;;
esac

enc_dir=$1
unenc_dir_given=false
mount_public=false
if [ ! -z "$2" ]; then
    unenc_dir_given=true
    unenc_dir=$2
    for arg in "$@" ; do
	if [ "$arg" = "-p" ]; then
	    mount_public=true
	fi
    done
    [ -d "$unenc_dir" ] || mkdir -- "$unenc_dir"
else
    unenc_dir=$(mktemp -d .XXXXXXXX)
fi

if [ ! -d "$enc_dir" ]; then
    mkdir -- "$enc_dir"
fi

enc_dir=$(canonicalize "$enc_dir")
unenc_dir=$(canonicalize "$unenc_dir")

# clear command-line argument list; hereafter used for options
set --
if [ "$unenc_dir_given" = "true" ]; then
    if [ "$mount_public" = "true" ]; then
	set -- -- -o allow_other
    fi
fi

# Attach the directory and change into it
if encfs "$enc_dir" "$unenc_dir" "$@"; then :; else
    echo "encfs failed"
    rmdir -- "$unenc_dir"
    exit 1
fi
if ! [ "$unenc_dir_given" = "true" ]; then
    chmod 700 "$unenc_dir"
fi
echo "Directory is $unenc_dir" >&2
cd "$unenc_dir" || exit

# Fall back to umount if fusermount is not available (e.g., on OS X)
FUSE_UMOUNT="$(command -v fusermount)"
FUSE_UMOUNT="${FUSE_UMOUNT:+fusermount -u}"
FUSE_UMOUNT="${FUSE_UMOUNT:-umount}"

# Honor the SHELL environment variable to select a shell to run
"$SHELL"; retval=$?

# ensure that this shell isn't itself holding the mounted directory open
# ...but avoid terminating on failure, *or* causing a shellcheck warning for
#    failing to check exit status from cd.
cd / ||:

# Note that there are two ways FUSE_UMOUNT can be parsed:
# - With eval (process command substitutions, redirections, etc., and honors
#   quotes; should only be done with human-generated/reviewed/trusted content,
#   see [BashFAQ #48](http://mywiki.wooledge.org/BashFAQ/048))
# - Without (can't run all possible commands this way, see
#   [BashFAQ #50](http://mywiki.wooledge.org/BashFAQ/050)).
#
# Since the expectation is that this will be user-controlled, flexibility is
# presumably more important than security, so opting for the eval approach.

eval "$FUSE_UMOUNT \"\$unenc_dir\"" # Call hook, honoring any shell syntax/quotes/&c. in same
if ! [ "$unenc_dir_given" = true ]; then
	rmdir -- "$unenc_dir"
fi
exit "$retval"
